### PR TITLE
Add basemap full bit depth streaming examples

### PR DESCRIPTION
**Pull request by joferkington**
Now that full bit depth streaming is officially released and documented at https://developers.planet.com/docs/basemaps/tile-services/xyz/, it would be good to have some examples of using it in various ways.  This PR adds an overview of streaming basemap data for both visualization and analysis and adds a use-case example of doing burn scar mapping using streamed mosaics with no need for activation or download.

Note that it's likely easiest to review the notebooks by inspecting the rendered versions at https://github.com/planetlabs/notebooks/blob/d5c0cd161854fc3ce71dcc8044832aca5c322d0a/jupyter-notebooks/Basemaps-API/streaming.ipynb and https://github.com/planetlabs/notebooks/blob/d5c0cd161854fc3ce71dcc8044832aca5c322d0a/jupyter-notebooks/use-cases/burned-area-delineation/park_fire.ipynb instead of the normal review of the raw file contents.

### CODE REVIEW

**Comment by olepinard** [comment]
Hi @joferkington, this is a great addition to the notebooks repo. I did run into some issues while running the notebook. When running the first cell block of the `streamig.ipynb` I am getting the following error 

> `ERROR 4: /Users/octave.lepinard/.cache/gdalwmscache/eb66c5f6eb9bbaf3d936f5423fb793a4/8/e/8eaa9164f4b6ea9d9bd20395eaab716d: No such file or directory
> ERROR 1: GDALWMS: Unable to open downloaded block.
> ERROR 1: GDALWMS: Unable to download block 26, 9.
> URL: Could not resolve host: tiles.planet.com
>   HTTP status code: 0, error: Could not resolve host: tiles.planet.com.
> Add the HTTP status code to <ZeroBlockHttpCodes> to ignore this error (see http://www.gdal.org/frmt_wms.html).
> ERROR 1: GDAL_WMS>, band 1: IReadBlock failed at X offset 25, Y offset 9: GDALWMS: Unable to download block 26, 9.
> URL: Could not resolve host: tiles.planet.com
>   HTTP status code: 0, error: Could not resolve host: tiles.planet.com.
> Add the HTTP status code to <ZeroBlockHttpCodes> to ignore this error (see http://www.gdal.org/frmt_wms.html).
> ERROR 1: IReadBlock failed at X offset 3, Y offset 7: GDAL_WMS>, band 1: IReadBlock failed at X offset 25, Y offset 9: GDALWMS: Unable to download block 26, 9.
> URL: Could not resolve host: tiles.planet.com
>   HTTP status code: 0, error: Could not resolve host: tiles.planet.com.
> Add the HTTP status code to <ZeroBlockHttpCodes> to ignore this error (see http://www.gdal.org/frmt_wms.html).`

However everytime I run it, it progresses further along until it is fully done after about 5 runs. Not sure if that is just due to the office wifi or if you might know why that is happening. In general I wonder if using gdalwrap might be a bit out of range of a lot of the users since it involves having gdal installed on the computer which not everyone has. Even though other notebooks use gdal I think if its available it makes a notebook more accessible to not use it. Your call though!

**Comment by joferkington** [comment]
@olepinard - It sounds like you're having local DNS issues.  "Could not resolve host" indicates issues with your local network.

**Comment by joferkington** [comment]
As for using `gdalwarp`, that's a good point. I'll add a note that it's optional.  I still think it's very useful to show examples of how to use standard and widely used tools.  While it's not likely true of the audience for this repo, in general there are likely more folks with gdal CLI tools installed than with `rasterio` + a full python environment installed. (Though obviously, if you're using this repo, then the opposite is likely true, as you wouldn't use this without a full python environment.)

**Comment by olepinard** [comment]
Fixed a couple typos and added a few comments to functions in order to be easier for less experienced coders to follow. This is a really awesome demo! Could this be used to bypass download quota if you can run all of this analysis through streaming? Does this mean that you can also save the full bit depth output as a geotiff?

**Comment by joferkington** [comment]
@olepinard - There is no download quota at all.  Streaming is metered, download isn't.  So it's the other way around. It helps ensure folks stay within quota instead of only using fully unlimited download.

**Review by olepinard — APPROVED** [review]
Looks great!

**Comment by joferkington** [comment]
Thanks!

**Pull request merged**
