### PR TITLE
Add yield forecasting notebook

### PR DESCRIPTION
**Pull request by thomasfrederikse**
We have created an example notebook on how to use Planetary Variables to make yield forecasts. See also issue https://github.com/planetlabs/notebooks/issues/357

### CODE REVIEW

**Comment by thomasfrederikse** [comment]
@yoann-malbeteau @matthew-ballard Could one of you review of this notebook to get it ready for merging?

**Comment by yoann-malbeteau** [comment]
I have few comments
- I would call it "Regional Yield Forecast" to avoid confusion with field yield forecast (that include farmers practices)
- Rather than adding the CSVs, would it be better to use the SH stat API (or Planet API) to extract the timeseries ? 
- Are you trying to showcase the yield_forecast bundles ? If so, I could be better to explain how you get the data ?  Ideally, using a region within the sandbox.
- Planet_style is not available to external user. I would remove it.
- in the figure for LST why do you plot both ? can you just invert the y axis (rather than put the value to negative) I can be confusing. 
- Why do you need two types of correlation ?
- Would it be better to "forecast 2022 and 2023" as a validation and then finish with the 2024 "real" forecast ?
- To improve readability: I would be nice to have the explanation for each variable at the beginning (like in a format of Why? about yield forecast?, what? PVs and How ? forecast model) and then we can jump directly into the yield forecast exercise.

**Comment by thomasfrederikse** [comment]
Thanks! I just updated the notebook with your comments in mind. See below:

_- I would call it "Regional Yield Forecast" to avoid confusion with field yield forecast (that include farmers practices)_ 
Done
_- Rather than adding the CSVs, would it be better to use the SH stat API (or Planet API) to extract the timeseries ? Are you trying to showcase the yield_forecast bundles ? If so, I could be better to explain how you get the data ? Ideally, using a region within the sandbox._ 
Good point. I chose this region because of the availability of yield data from USDA. VOD is not available as sandbox data at all. Furthermore, obtaining the data would add massive chunks of code to the notebook, which reduces the readability, as we just want to show how a simple forecasting algorithm could look. Therefore, I added the time series to the notebook. 
_- Planet_style is not available to external user. I would remove it._ 
Double-checked: the code also works without using planet_style and the plots show up good.
_- in the figure for LST why do you plot both ? can you just invert the y axis (rather than put the value to negative) I can be confusing._ 
Yes, that’d be much better. I updated the plots
_- Why do you need two types of correlation ?_ 
Some people prefer the Spearman rank correlation over the standard Pearson coefficient. The differences between both are rather small, but for the sake of completeness, I’ve listed both. 
_- Would it be better to "forecast 2022 and 2023" as a validation and then finish with the 2024 "real" forecast ? Yes, that’s better._ 
Done
_- To improve readability: I would be nice to have the explanation for each variable at the beginning (like in a format of Why? about yield forecast?, what? PVs and How ? forecast model) and then we can jump directly into the yield forecast exercise._ 
Yes, good idea. I’ve re-ordered the descriptions.

**Review by yoann-malbeteau — APPROVED** [review]
thank you. Very nice example

**Pull request merged**
