### PR TITLE
add gdd thermal time notebook

### PR DESCRIPTION
**Pull request by matthew-ballard**

### CODE REVIEW

**Comment by matthew-ballard** [comment]
incorporated feedback from @maddie-grady from slack:

1. GDD is probably the better term to use and would be more recognisable to the use case we present.
2. SWC range - the return on the swc_time_series_evalscript should be divided by 1000 instead of 100

**Comment by matthew-ballard** [comment]
ready for your review @maddie-grady!

**Review by maddie-grady — APPROVED** [review]

**Comment by maddie-grady** [comment]
GDD and thermal time are used interchangeably through out, is it worth standardizing on GDD, at least in the markdown?  I think that it's all understandable as is though as both terms are introduced at the top of the notebook.

**Comment by matthew-ballard** [comment]
good point, I changed some thermal time to gdd, but left too many in. added a new commit where I've changed all variables to be "gdd" and not "thermal_time" and fixed the few markdown/comments that were also remaining.

**Pull request merged**
