### PR TITLE
update readmes to link to image in dockerhub

### LINKED ISSUE #114: host docker image on dockerhub
to allow users to get up and running with notebooks as fast as possible, remove the requirement for building their own images by hosting a docker image on dockerhub

### PR DESCRIPTION
**Pull request by jreiberkyle**
closes #114

### CODE REVIEW

**Comment by sarasafavi** [comment]
:+1: SO EXCITING

**Comment by strixcuriosus** [comment]
This is awesome!

You can also skip the `docker pull` and `docker tag` steps by directly running
```
docker run -it --rm -p 8888:8888 -v $PWD:/home/jovyan/work -e PL_API_KEY='YOUR_API_KEY' planetlabs/notebooks
```
(which pulls the docker image if it doesn't exist locally)

**Comment by jreiberkyle** [comment]
@strixcuriosus yeah, great point! The reason I kept it in there is to rename the image to planet-notebooks, which is what it is called throughout the rest of the README. That was the lazy solution. I could have also updated planet-notebooks to planetlabs/notebooks and updated the tags in my docker system. With a little coaxing (aka if it would make anyone's life easier) I could be convinced to not be so lazy :)

**Comment by strixcuriosus** [comment]
@jreiberkyle that makes sense! Thanks for keeping the rest of the references sensible. 
It just seemed nice that we could have 1 fewer step for newcomers to get our notebooks to run, but the work you've already done in making one canonical image is fantastic! I'm glad the happy path no longer requires newcomers to build their own notebook image.

**Pull request merged**
