### PR TITLE
Cli to client data download devrel 919

### PR DESCRIPTION
**Pull request by mkshah605**
Change Outdated V1 CLI code for downloading data to V2 Client code.

This PR mainly focuses on changing broken CLI functionality to Client functionality.

What this PR DOES do:
- Fix outdated CLI code where new V2 CLI functionality is available
- Change outdated CLI code to V2 Client code where it makes sense to do so (at least until we have the needed CLI V2 functionality)

However, there are some exceptions to the scope of this ticket, and subsequent tickets created to address these:
- A few of these notebooks use Requests. This was a changed for a couple of them, but instances of this kept coming up so the remainder of the notebooks that use Requests will be addressed by [DEVREL-925](https://hello.planet.com/jira/browse/DEVREL-925)
- Some code was altered in the Label Geotiff notebook related to COG creation. This turned out to be a heavier task, and the remainder of it will be addressed in [DEVREL-923](https://hello.planet.com/jira/browse/DEVREL-923)
- Notebooks in the "Crop Classification",  "In-Class Exercises", and "UDM2" use data download functionality (now data asset-download) that is not yet implemented in the V2 CLI. These crop classification notebooks are interconnected and need a bit of overhauling anyways, and the in-class exercises notebooks are not very high touch, so instead of waiting for this CLI functionality to be implemented before making these changes, I thought it's best to make as much progress as possible with these for now and come back to it from a more "top-down" approach once we get there.The "In-Class Exercises" notebooks might not make the "final cut" during our upcoming notebooks rebranding. A new ticket has been created for the [UDM2 notebook](https://hello.planet.com/jira/browse/DEVREL-924) and [Crop Classification notebooks](https://hello.planet.com/jira/browse/DEVREL-949).
- In the Lamdsat-PS comparison notebook, the download works for our imagery using the CLI but not for Landsat. This is documented in both a [bug ticket](https://hello.planet.com/jira/browse/DEVREL-951), as well as an i[ssue specific to this notebook](https://hello.planet.com/jira/browse/DEVREL-950).

### CODE REVIEW

**Comment by jreiberkyle** [comment]
At this time, I don't feel like I have the bandwidth to read and review the entirety of the 7 notebooks. Do you have any specific lines you could point me to to help me focus my review? Or, alternatively, do you want me to review based on the PR description?

**Comment by mkshah605** [comment]
Adding some notes about which cells to check out for each notebook to get an idea of the changes made.

This is a little confusing, as a commit was added earlier today to address merge conflicts from a recent merge to master for another ticket.

- Labelmaker.ipynb: Jupyter cells 90-98
-

**Review by jreiberkyle — APPROVED** [review]
looks great! Tho there are some errors being shown in the output of the notebook that you may want to address. I remember one being about 'str' and path. Also, the UDM in the UDM notebook somehow looks worse than the original, like more cloud pixels. may want to investigate what that is.

**Comment by mkshah605** [comment]
Thanks Jen! I've made notes and created tickets (linked above) to address the remaining issues with code output.

**Pull request merged**
