### PR TITLE
update SDK build_request feature usage

### PR DESCRIPTION
**Pull request by mkshah605**
Added packages, displayed output, and changed usage of the order_requests feature.

A user was using this notebook and wondering why it wasn't working for her around Section 4.2. This may have been it.

### CODE REVIEW

**Comment by jreiberkyle** [comment]
hey @mkshah605, what kind of feedback would be helpful here? As I cannot easily diff the code, I don't have an easy way to review the specific changes you made. Would you like me to review based on the PR desc or just look over the notebook and review it as a whole?

**Comment by mkshah605** [comment]
@jreiberkyle this is a small one, and mostly created to try to address that user's issues (although it looks like they weren't actually related to the notebook after all LOL). The main changes are on lines 69 and 70 (package imports), and in 573 and 574 (fixing how the order_requests feature is used). The rest of the code changes you see are mostly just running the output of cells in the notebook.

There aren't really specific parts of this I'm looking for feedback on, a second pair of eyes on it before it's merged would be great!

**Comment by jreiberkyle** [comment]
@mkshah605 those two changes look good. The entire notebook is quite large and I don't feel I have the bandwidth to review all of it. Unless you have specific regions for me to look at, I feel comfortable deferring to you on the quality of the notebook as a whole.

**Review by jreiberkyle — APPROVED** [review]

**Comment by mkshah605** [comment]
Thank you @jreiberkyle !

**Pull request merged**
