### PR TITLE
Subscr ntbk devrel 886

### PR DESCRIPTION
**Pull request by mkshah605**
Create an Subscriptions API Quickstart Notebook demonstrating how to use Client functionality.

### CODE REVIEW

**Comment by jreiberkyle** [comment]
lgtm. With the following PR, `list_subscriptions` will become `list_subscriptions_aiter`

https://github.com/planetlabs/planet-client-python/pull/785

**Review by jreiberkyle — APPROVED** [review]
lgtm. With the following PR, `list_subscriptions` will become `list_subscriptions_aiter`

https://github.com/planetlabs/planet-client-python/pull/785

**Comment by mkshah605** [comment]
Thank you @jreiberkyle ! Made a note of those changes that need to be made in the following ticket, after it is pushed:
https://hello.planet.com/jira/browse/DEVREL-908

**Comment by jreiberkyle** [comment]
@cholmes / @mkshah605 / @JuLeeAtPlanet - I'm curious, what is the determining factor between having quick start code examples in notebooks instead of in the docs?

**Comment by mkshah605** [comment]
@jreiberkyle by code examples in the docs, do you mean something like [what is listed here](https://developers.planet.com/docs/subscriptions/) under "Example Request" ?

I think both are good but might have slightly different uses- I see the docs as a place people can go to for reference and it makes sense to have the API requests there so people can see how it works behind-the-scenes even if they might not be using it via the API directly. The notebooks would be a place where they could dig into it more, manipulate code, and see how it works more end-to-end in a hands-on way.

I think putting the examples that are in the notebooks, into the docs might be too much info and kind of distracting for people who are there for a quick reference. If we did this we might need to consider restructuring the devcenter to have both "reference" and "examples" info.

That being said, I do think we should reference the notebooks more in the actual docs themselves, so that people are able to find them if the docs aren't enough (and vice-versa, the docs are referenced in the notebooks as well).

I think this is an important topic, happy to discuss more and eager to know y'all's thoughts!

**Comment by cholmes** [comment]
I think we should definitely have 'both'. And agree we should link to the subscriptions notebooks until we have something in the docs. 

I think the difference is probably fuzzy, but I'd say with notebooks they should really be 'designed' for like a 'copy & paste' user - count on someone just taking it and changing the parameters for what they need, without really understanding what's going on. I've talked to several users who make use of notebooks that way. For the docs I see the audience being more of a reasonable python dev - getting across the main info they need to go to get started, but not needing to show every step. And ideally the two complement one another - aren't exactly the same, so those who are trying to go from 'copy and paste' to be a more confident dev can see at least a couple different examples of how things are done, and can learn a bit from their differences.

Related is something that @JuLeeAtPlanet and I talked about recently, which is the purpose of the 'core' docs on developers.planet.com. My ideal is that those are pure JSON + endpoint, without any programming language involved, to give anyone a sense of what the requests and responses are.

**Pull request merged**
