### PR TITLE
Added evalscript notebooks

### PR DESCRIPTION
**Pull request by jonasViehweger**
I would appreciate if it could be checked for typos and formatting. Cells should all work, but if they can be run again on a different machine that would also be good!

### CODE REVIEW

**Comment by matthew-ballard** [comment]
These are great resources! One suggestion - I think that we should make Sentinel Hub APIs top-level to be in line with all of the Planet APIs, instead of isolated to their own folder. This might make it hard to find, but I think that it can make this feel like one platform and prevent changing the URLs in the future.

**Comment by matthew-ballard** [comment]
@jonasViehweger are you still looking to publish this? I know you didn't ask for my review😄, but I went through it and it looks great, no comments from me. Happy to approve if you'd like?

my other comment about elevating this out of the SH folder can come later I think

**Comment by jonasViehweger** [comment]
Hey Matt, thanks for circling back on this and having a look over it. I'm happy with any third party having a look over it, so I added you as a reviewer. If you can give an approving review then I can merge it.

I'll leave the folder reorg to you, since I am not sure how this would be done best (e.g. where would the notebook that I added go? Since Evalscripts are not an API, but used in many different APIs.)

**Comment by matthew-ballard** [comment]
We can table the reorganization of it for later this year, since I don't have a POV on how best to organize it, and it's not essential. approved this and we can revisit later

**Review by matthew-ballard — APPROVED** [review]
look great!

**Pull request merged**
